---
- name: 确保 /data 目录存在
  file:
    path: /data
    state: directory

- name: 下载 Miniconda 安装程序
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/Miniconda3-latest-Linux-x86_64.sh
    mode: '0755'

- name: 安装 Miniconda
  command: /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /data/miniconda
  args:
    creates: /data/miniconda/bin/conda

- name: 初始化 conda
  shell: /data/miniconda/bin/conda init
  args:
    executable: /bin/bash

- name: 将 conda 添加到环境变量
  lineinfile:
    path: /etc/profile.d/conda.sh
    create: yes
    line: 'export PATH="/data/miniconda/bin:$PATH"'
    state: present

- name: 配置 conda 使用清华镜像源
  shell: |
    /data/miniconda/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
    /data/miniconda/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
    /data/miniconda/bin/conda config --set show_channel_urls yes

- name: 关闭自动激活 base 环境
  shell: /data/miniconda/bin/conda config --set auto_activate_base false

- name: 清理 Miniconda 安装程序
  file:
    path: /tmp/Miniconda3-latest-Linux-x86_64.sh
    state: absent
