---
- name: 获取当前时间戳
  ansible.builtin.command: date +%Y%m%d%H%M%S
  register: current_timestamp

- name: 备份sources.list
  ansible.builtin.copy:
    src: /etc/apt/sources.list
    dest: /etc/apt/sources.list.{{ current_timestamp.stdout }}

- name: 替换镜像源为阿里云
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: 'http://.*.ubuntu.com'
    replace: 'http://mirrors.aliyun.com'

- name: 更新软件源缓存
  ansible.builtin.apt:
    update_cache: yes
  register: apt_update_result
  retries: 3
  delay: 5
  until: apt_update_result is success
