---
- name: Check kernel version
  hosts: all
  become: yes
  tasks:
    - name: Get kernel version
      command: uname -r
      register: kernel_version

    - name: Extract kernel version before the dash
      set_fact:
        kernel_version_extracted: "{{ kernel_version.stdout.split('-')[0] }}"

    - name: Print extracted kernel version
      debug:
        msg: "Kernel version is {{ kernel_version_extracted }}"

    - name: Check if kernel version is greater than 4.17
      fail:
        msg: "Kernel version must be greater than 4.17. Current version: {{ kernel_version_extracted }}"
      when: "kernel_version_extracted is version('4.17', '<=')"