---
- name: Install JDK, Redis, and MySQL
  hosts: 192.168.56.62
  become: yes

  vars:
    jdk_version: "11"
    redis_version: "6.2.6"
    redis_password: "your_redis_password"
    mysql_root_password: "your_root_password"
    mysql_user: "your_mysql_user"
    mysql_password: "your_mysql_password"
    mysql_database: "your_database"

  tasks:
    - name: Install JDK on Debian
      apt:
        name: "openjdk-{{ jdk_version }}-jdk"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install JDK on CentOS
      yum:
        name: "java-{{ jdk_version }}-openjdk"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Redis on Debian
      apt:
        name: redis-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Redis on CentOS
      yum:
        name: redis
        state: present
      when: ansible_os_family == "RedHat"

    - name: Configure Redis to allow remote connections on Debian
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^#?bind'
        line: 'bind 0.0.0.0'
        state: present
      when: ansible_os_family == "Debian"
      notify: Restart Redis

    - name: Configure Redis to allow remote connections on CentOS
      lineinfile:
        path: /etc/redis.conf
        regexp: '^#?bind'
        line: 'bind 0.0.0.0'
        state: present
      when: ansible_os_family == "RedHat"
      notify: Restart Redis

    - name: Configure Redis password on Debian
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^#?requirepass'
        line: "requirepass {{ redis_password }}"
        state: present
      when: ansible_os_family == "Debian"
      notify: Restart Redis

    - name: Configure Redis password on CentOS
      lineinfile:
        path: /etc/redis.conf
        regexp: '^#?requirepass'
        line: "requirepass {{ redis_password }}"
        state: present
      when: ansible_os_family == "RedHat"
      notify: Restart Redis

    - name: Ensure Redis is started and enabled on Debian
      service:
        name: redis-server
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Redis is started and enabled on CentOS
      service:
        name: redis
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Install MySQL on Debian
      apt:
        name: mysql-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Install MySQL on CentOS
      yum:
        name: mysql-server
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure MySQL is started and enabled on Debian
      service:
        name: mysql
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Ensure MySQL is started and enabled on CentOS
      service:
        name: mysqld
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Allow MySQL remote connections
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present
      when: ansible_os_family == "Debian"
      notify: Restart MySQL

    - name: Allow MySQL remote connections on CentOS
      lineinfile:
        path: /etc/my.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present
      when: ansible_os_family == "RedHat"
      notify: Restart MySQL

    - name: Install ansible python3 mysql dependency on Debian
      apt:
        name: python3-mysqldb
        state: latest
      when: ansible_os_family == "Debian"

    - name: Install ansible python3 mysql dependency on CentOS
      yum:
        name: python3-PyMySQL
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Set MySQL root password
      mysql_user:
        login_user: root
        login_password: ''
        user: root
        password: "{{ mysql_root_password }}"
        host_all: yes
        state: present

    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        host: '%'
        state: present

    - name: Open firewall for MySQL and Redis on Debian
      ufw:
        rule: allow
        name: '{{ item }}'
      with_items:
        - '3306'
        - '6379'
      when: ansible_os_family == "Debian"

    - name: Open firewall for MySQL and Redis on CentOS
      firewalld:
        port: '{{ item }}/tcp'
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - '3306'
        - '6379'
      when: ansible_os_family == "RedHat"

  handlers:
    - name: Restart Redis
      service:
        name: "{{ 'redis-server' if ansible_os_family == 'Debian' else 'redis' }}"
        state: restarted

    - name: Restart MySQL
      service:
        name: "{{ 'mysql' if ansible_os_family == 'Debian' else 'mysqld' }}"
        state: restarted
