---
- name: Remove MySQL
  hosts: 192.168.56.62
  become: yes
  tasks:
    - name: Remove MySQL server package
      apt:
        name: mysql-server
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove MySQL client package
      apt:
        name: mysql-client
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove MySQL common package
      apt:
        name: mysql-common
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove MySQL server package
      yum:
        name: mysql-server
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove MySQL client package
      yum:
        name: mysql
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove MySQL common package
      yum:
        name: mysql-common
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove MySQL configuration files
      file:
        path: /etc/mysql
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove MySQL data directory
      file:
        path: /var/lib/mysql
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove MySQL configuration files
      file:
        path: /etc/my.cnf
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove MySQL data directory
      file:
        path: /var/lib/mysql
        state: absent
      when: ansible_os_family == "RedHat"