---
- hosts:
  - all
  gather_facts: false
  tasks:
    - name: Ensure group "autox" exists
      ansible.builtin.group:
        name: autox
        state: present
    - name: Add the user 'autox' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: autox
        password: "{{ 'autox' | password_hash('sha512') }}"
        shell: /bin/bash
        group: autox
        append: yes
        state: present
      no_log: true
    - name: Allow the autox user to run any commands as alice with sudo -u root
      community.general.sudoers:
        name: autox-do-as-root
        state: present
        user: autox
        runas: root
        commands: ALL
    - block:
      - name: 判断 ufw 是否安装
        shell: >
          systemctl is-active ufw | grep active || echo "not be found"
        register: ufw_already_installed

      - name: 禁用防火墙
        service:
          name: ufw
          state: stopped
          enabled: no
        when: ufw_already_installed.stdout == "active"
      when: "firewalld_disabled | default(True) | bool"

